ALTER TABLE "Business"
ADD COLUMN "promotionScheduleType" TEXT NOT NULL DEFAULT 'one_off',
ADD COLUMN "promotionWeeklyDays" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN "promotionMonthlyWeeks" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[];

ALTER TABLE "Promotion"
ADD COLUMN "scheduleType" TEXT NOT NULL DEFAULT 'one_off',
ADD COLUMN "weeklyDays" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN "monthlyWeeks" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[];
