import { RegionalStoreSeed, seedRegionalStores } from "./lib/seed-regional-stores";

const officialUrl = "https://www.skechers.com.au/";
const saleUrl = "https://www.skechers.com.au/sale";
const saleCatalogs = [
  saleUrl,
  "https://www.skechers.com.au/women/sale",
  "https://www.skechers.com.au/men/sale",
];

const stores: RegionalStoreSeed[] = [
  {
    name: "Skechers World Square",
    url: `${officialUrl}#world-square-sydney-nsw`,
    websiteUrl: officialUrl,
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "World Square, 644 George Street, Sydney NSW 2000",
    catalogs: saleCatalogs,
    description: "Official Skechers Australia store listing for lifestyle, walking, work and performance footwear.",
  },
  {
    name: "Skechers Westfield Chatswood",
    url: `${officialUrl}#westfield-chatswood-nsw`,
    websiteUrl: officialUrl,
    suburb: "Chatswood",
    city: "Sydney",
    state: "NSW",
    address: "Westfield Chatswood, 1 Anderson Street, Chatswood NSW 2067",
    catalogs: saleCatalogs,
    description: "Official Skechers Australia store listing for lifestyle, walking, work and performance footwear.",
  },
  {
    name: "Skechers Westfield Penrith",
    url: `${officialUrl}#westfield-penrith-nsw`,
    websiteUrl: officialUrl,
    suburb: "Penrith",
    city: "Sydney",
    state: "NSW",
    address: "Westfield Penrith, 585 High Street, Penrith NSW 2750",
    catalogs: saleCatalogs,
    description: "Official Skechers Australia store listing for lifestyle, walking, work and performance footwear.",
  },
  {
    name: "Skechers Westfield Miranda",
    url: `${officialUrl}#westfield-miranda-nsw`,
    websiteUrl: officialUrl,
    suburb: "Miranda",
    city: "Sydney",
    state: "NSW",
    address: "Westfield Miranda, 600 Kingsway, Miranda NSW 2228",
    catalogs: saleCatalogs,
    description: "Official Skechers Australia store listing for lifestyle, walking, work and performance footwear.",
  },
  {
    name: "Skechers Chadstone",
    url: `${officialUrl}#chadstone-vic`,
    websiteUrl: officialUrl,
    suburb: "Chadstone",
    city: "Melbourne",
    state: "VIC",
    address: "Chadstone The Fashion Capital, 1341 Dandenong Road, Chadstone VIC 3148",
    catalogs: saleCatalogs,
    description: "Official Skechers Australia store listing for lifestyle, walking, work and performance footwear.",
  },
  {
    name: "Skechers Elizabeth Street Melbourne",
    url: `${officialUrl}#elizabeth-street-melbourne-vic`,
    websiteUrl: officialUrl,
    suburb: "Melbourne CBD",
    city: "Melbourne",
    state: "VIC",
    address: "104-106 Elizabeth Street, Melbourne VIC 3000",
    catalogs: saleCatalogs,
    description: "Official Skechers Australia store listing for lifestyle, walking, work and performance footwear.",
  },
  {
    name: "Skechers Pacific Werribee",
    url: `${officialUrl}#pacific-werribee-vic`,
    websiteUrl: officialUrl,
    suburb: "Werribee",
    city: "Melbourne",
    state: "VIC",
    address: "Pacific Werribee, Derrimut Road, Werribee VIC 3030",
    catalogs: saleCatalogs,
    description: "Official Skechers Australia store listing for lifestyle, walking, work and performance footwear.",
  },
  {
    name: "Skechers Pacific Fair",
    url: `${officialUrl}#pacific-fair-qld`,
    websiteUrl: officialUrl,
    suburb: "Broadbeach",
    city: "Gold Coast",
    state: "QLD",
    address: "Pacific Fair Shopping Centre, Hooker Boulevard, Broadbeach QLD 4218",
    catalogs: saleCatalogs,
    description: "Official Skechers Australia store listing for lifestyle, walking, work and performance footwear.",
  },
  {
    name: "Skechers Adelaide",
    url: `${officialUrl}#adelaide-sa`,
    websiteUrl: officialUrl,
    suburb: "Adelaide",
    city: "Adelaide",
    state: "SA",
    address: "430 King William Street, Adelaide SA 5000",
    catalogs: saleCatalogs,
    description: "Official Skechers Australia store listing for lifestyle, walking, work and performance footwear.",
  },
  {
    name: "Skechers Westfield Carousel",
    url: `${officialUrl}#westfield-carousel-wa`,
    websiteUrl: officialUrl,
    suburb: "Cannington",
    city: "Perth",
    state: "WA",
    address: "Westfield Carousel, 1382 Albany Highway, Cannington WA 6107",
    catalogs: saleCatalogs,
    description: "Official Skechers Australia store listing for lifestyle, walking, work and performance footwear.",
  },
  {
    name: "Skechers at Myer",
    url: "https://www.myer.com.au/b/Skechers",
    websiteUrl: "https://www.myer.com.au/b/Skechers",
    suburb: "Australia",
    city: "Online",
    state: "National",
    address: "Myer online Skechers brand page",
    catalogs: ["https://www.myer.com.au/b/Skechers"],
    description: "Skechers shoes stocked by Myer Australia.",
    locationSource: "online",
    ignoredOfferUrlPatterns: [/\/sale(?:[/?#]|$)/i],
  },
  {
    name: "Skechers at David Jones",
    url: "https://www.davidjones.com/brand/skechers",
    websiteUrl: "https://www.davidjones.com/brand/skechers",
    verificationUrl: "https://www.davidjones.com/shop/skechers-sale",
    suburb: "Australia",
    city: "Online",
    state: "National",
    address: "David Jones online Skechers brand page",
    catalogs: ["https://www.davidjones.com/brand/skechers", "https://www.davidjones.com/shop/skechers-sale"],
    description: "Skechers shoes stocked by David Jones Australia.",
    locationSource: "online",
    ignoredOfferUrlPatterns: [/\/sale(?:[/?#]|$)/i],
  },
  {
    name: "Skechers at JD Sports",
    url: "https://www.jdsports.com.au/search/skechers/",
    websiteUrl: "https://www.jdsports.com.au/search/skechers/",
    suburb: "Australia",
    city: "Online",
    state: "National",
    address: "JD Sports Australia online Skechers search page",
    catalogs: ["https://www.jdsports.com.au/search/skechers/"],
    description: "Skechers shoes stocked by JD Sports Australia.",
    locationSource: "online",
    ignoredOfferUrlPatterns: [/\/sale(?:[/?#]|$)/i],
  },
  {
    name: "Skechers at Foot Locker",
    url: "https://www.footlocker.com.au/en/search?query=skechers",
    websiteUrl: "https://www.footlocker.com.au/en/search?query=skechers",
    suburb: "Australia",
    city: "Online",
    state: "National",
    address: "Foot Locker Australia online Skechers search page",
    catalogs: ["https://www.footlocker.com.au/en/search?query=skechers"],
    description: "Skechers shoes stocked by Foot Locker Australia.",
    locationSource: "online",
    ignoredOfferUrlPatterns: [/\/sale(?:[/?#]|$)/i],
  },
  {
    name: "Skechers at The Athlete's Foot",
    url: "https://www.theathletesfoot.com.au/brands/skechers.html",
    websiteUrl: "https://www.theathletesfoot.com.au/brands/skechers.html",
    suburb: "Australia",
    city: "Online",
    state: "National",
    address: "The Athlete's Foot Australia Skechers brand page",
    catalogs: ["https://www.theathletesfoot.com.au/brands/skechers.html"],
    description: "Skechers shoes stocked by The Athlete's Foot Australia.",
    locationSource: "online",
    ignoredOfferUrlPatterns: [/\/sale(?:[/?#]|$)/i],
  },
  {
    name: "Skechers at Hype DC",
    url: "https://www.hypedc.com/au/search?q=skechers",
    websiteUrl: "https://www.hypedc.com/au/search?q=skechers",
    suburb: "Australia",
    city: "Online",
    state: "National",
    address: "Hype DC Australia online Skechers search page",
    catalogs: ["https://www.hypedc.com/au/search?q=skechers"],
    description: "Skechers shoes stocked by Hype DC Australia.",
    locationSource: "online",
    ignoredOfferUrlPatterns: [/\/(?:categories\/)?sale(?:[/?#]|$)/i, /\/brands\/[^/]+\/sale(?:[/?#]|$)/i],
  },
  {
    name: "Skechers at Platypus",
    url: "https://www.platypusshoes.com.au/search?q=skechers",
    websiteUrl: "https://www.platypusshoes.com.au/search?q=skechers",
    suburb: "Australia",
    city: "Online",
    state: "National",
    address: "Platypus Shoes Australia online Skechers search page",
    catalogs: ["https://www.platypusshoes.com.au/search?q=skechers"],
    description: "Skechers shoes stocked by Platypus Australia.",
    locationSource: "online",
    ignoredOfferUrlPatterns: [/\/sale(?:[/?#]|$)/i],
  },
];

seedRegionalStores({
  regionName: "Australia",
  categoryName: "Clothing & Fashions",
  verifierProfile: "retailShop",
  stores,
  maxPages: 8,
  requestTimeoutMs: 15000,
  concurrency: 3,
}).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
