import { DiningBeverageVenue, seedDiningBeverageRegion } from "./lib/seed-dining-beverages-region";

const venues: DiningBeverageVenue[] = [
  {
    name: "Africola Adelaide",
    url: "https://africola.com.au/",
    suburb: "Adelaide",
    city: "Adelaide",
    state: "SA",
    address: "4 East Terrace, Adelaide SA 5000",
    catalogs: ["https://africola.com.au/"],
    description: "Adelaide restaurant and bar serving bold dinner menus, drinks and high-energy dining.",
  },
  {
    name: "Shobosho Adelaide",
    url: "https://shobosho.com.au/",
    suburb: "Adelaide",
    city: "Adelaide",
    state: "SA",
    address: "17 Leigh Street, Adelaide SA 5000",
    catalogs: ["https://shobosho.com.au/"],
    description: "Adelaide Japanese-inspired restaurant and bar serving lunch, dinner and charcoal cooking.",
  },
  {
    name: "Fugazzi Adelaide",
    url: "https://fugazzi.com.au/",
    suburb: "Adelaide",
    city: "Adelaide",
    state: "SA",
    address: "27 Leigh Street, Adelaide SA 5000",
    catalogs: ["https://fugazzi.com.au/"],
    description: "Adelaide Italian restaurant and bar serving lunch, dinner, cocktails and private dining.",
  },
  {
    name: "2KW Bar and Restaurant Adelaide",
    url: "https://2kwbar.com.au/",
    suburb: "Adelaide",
    city: "Adelaide",
    state: "SA",
    address: "2 King William Street, Adelaide SA 5000",
    catalogs: ["https://2kwbar.com.au/", "https://2kwbar.com.au/whats-on/"],
    description: "Adelaide rooftop bar and restaurant serving lunch, dinner, cocktails and skyline drinks.",
  },
  {
    name: "Hains and Co Adelaide",
    url: "https://hainsco.com.au/",
    suburb: "Adelaide",
    city: "Adelaide",
    state: "SA",
    address: "23 Gilbert Place, Adelaide SA 5000",
    catalogs: ["https://hainsco.com.au/"],
    description: "Adelaide cocktail and gin bar serving drinks, cigars and late-night city hospitality.",
  },
  {
    name: "Maybe Mae Adelaide",
    url: "https://maybemae.com/",
    suburb: "Adelaide",
    city: "Adelaide",
    state: "SA",
    address: "15 Peel Street, Adelaide SA 5000",
    catalogs: ["https://maybemae.com/"],
    description: "Hidden Adelaide cocktail bar serving crafted drinks and intimate late-night hospitality.",
  },
  {
    name: "Trap Cocktail Bar Adelaide",
    url: "https://www.trapadl.com/",
    suburb: "Adelaide",
    city: "Adelaide",
    state: "SA",
    address: "Cold Chisel Lane, Adelaide SA 5000",
    catalogs: ["https://www.trapadl.com/"],
    description: "Underground Adelaide cocktail bar with music, events, drinks and late-night venue energy.",
  },
  {
    name: "Makan Wine Bar Adelaide",
    url: "https://makanwinebar.com/",
    suburb: "Adelaide",
    city: "Adelaide",
    state: "SA",
    address: "Adelaide SA 5000",
    catalogs: ["https://makanwinebar.com/"],
    description: "Asian fusion restaurant and wine bar with happy hour, live music, themed events and dinner service.",
  },
  {
    name: "Apoteca Bar and Restaurant Adelaide",
    url: "https://apoteca.com.au/",
    suburb: "Adelaide",
    city: "Adelaide",
    state: "SA",
    address: "118 Hindley Street, Adelaide SA 5000",
    catalogs: ["https://apoteca.com.au/"],
    description: "Adelaide bar and restaurant with cellar dining, wine, cocktails and private function spaces.",
  },
  {
    name: "Distill Adelaide",
    url: "https://www.distilladelaide.au/",
    suburb: "Adelaide",
    city: "Adelaide",
    state: "SA",
    address: "286 Rundle Street, Adelaide SA 5000",
    contact: "08 8227 0825",
    catalogs: ["https://www.distilladelaide.au/"],
    description: "Adelaide cocktail and wine bar with DJs, themed nights and evening entertainment.",
  },
];

seedDiningBeverageRegion("South Australia", venues).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
