import { RegionalStoreSeed, seedRegionalStores } from "./lib/seed-regional-stores";

const stores: RegionalStoreSeed[] = [
  {
    name: "Oroton Outlet",
    url: "https://oroton.com/outlet/",
    websiteUrl: "https://oroton.com/",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: ["https://oroton.com/outlet/"],
    description: "Australian designer accessories outlet with bags, wallets, apparel and outlet specials.",
  },
  {
    name: "Coach Outlet Australia",
    url: "https://au.coach.com/shop/outlet",
    websiteUrl: "https://au.coach.com/",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: [
      "https://au.coach.com/shop/outlet",
      "https://au.coach.com/shop/outlet/clearance/view-all?filterCategory=Bags",
    ],
    description: "Coach Australia outlet and clearance range for bags, wallets and accessories.",
  },
  {
    name: "Country Road & Trenery Outlet",
    url: "https://outlet.countryroad.com.au/",
    suburb: "Eastern Creek",
    city: "Sydney",
    state: "NSW",
    address: "Eastern Creek NSW 2766",
    catalogs: ["https://outlet.countryroad.com.au/"],
    description: "Country Road and Trenery outlet shopping for fashion, homewares and seasonal clearance.",
  },
  {
    name: "M.J. Bale Outlet Stores",
    url: "https://www.mjbale.com/pages/outlet-stores",
    websiteUrl: "https://www.mjbale.com/",
    suburb: "Homebush",
    city: "Sydney",
    state: "NSW",
    address: "Homebush NSW 2140",
    catalogs: ["https://www.mjbale.com/collections/outlet"],
    description: "M.J. Bale outlet and menswear clearance for suits, shirts, jackets and accessories.",
  },
  {
    name: "Politix Canberra Outlet",
    url: "https://www.politix.com.au/stores/ACT-Canberra-Outlet-Centre",
    websiteUrl: "https://www.politix.com.au/",
    suburb: "Fyshwick",
    city: "Canberra",
    state: "ACT",
    address: "Canberra Outlet Centre, 337 Canberra Avenue, Fyshwick ACT 2609",
    catalogs: ["https://www.politix.com.au/sale"],
    description: "Politix outlet store at Canberra Outlet Centre with menswear sale and outlet offers.",
  },
  {
    name: "Skechers Canberra Outlet",
    url: "https://canberraoutlet.com.au/stores/skechers",
    websiteUrl: "https://www.skechers.com.au/",
    suburb: "Fyshwick",
    city: "Canberra",
    state: "ACT",
    address: "Canberra Outlet Centre, 337 Canberra Avenue, Fyshwick ACT 2609",
    catalogs: ["https://www.skechers.com.au/sale"],
    description: "Skechers outlet store and online sale for shoes, sneakers and active footwear.",
  },
  {
    name: "Superdry Outlet",
    url: "https://www.superdry.com/outlet/",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: ["https://www.superdry.com/outlet/"],
    description: "Superdry outlet with clothing, jackets and seasonal fashion markdowns.",
  },
  {
    name: "Ted Baker Outlet",
    url: "https://www.tedbaker.com/collections/outlet",
    suburb: "Melbourne CBD",
    city: "Melbourne",
    state: "VIC",
    address: "Melbourne VIC 3000",
    catalogs: ["https://www.tedbaker.com/collections/outlet"],
    description: "Ted Baker outlet collection with fashion, accessories and clearance offers.",
  },
  {
    name: "Armani Exchange Outlet Australia",
    url: "https://www.armani.com/en-au/armani-exchange/outlet/",
    websiteUrl: "https://www.armani.com/en-au/armani-exchange/",
    suburb: "South Wharf",
    city: "Melbourne",
    state: "VIC",
    address: "South Wharf VIC 3006",
    catalogs: ["https://www.armani.com/en-au/armani-exchange/outlet/"],
    description: "Armani Exchange Australian outlet range with fashion and accessories markdowns.",
  },
  {
    name: "BOSS Outlet Homebush",
    url: "https://www.hugoboss.com/au/boss-outlet-3-1-5-underwood-road-sydney-homebush-nsw/",
    websiteUrl: "https://www.hugoboss.com/au/",
    suburb: "Homebush",
    city: "Sydney",
    state: "NSW",
    address: "3-5 Underwood Road, Homebush NSW 2140",
    catalogs: ["https://www.hugoboss.com/au/sale/"],
    description: "BOSS outlet store in Homebush with premium menswear and womenswear sale offers.",
  },
  {
    name: "Arc'teryx Outlet Australia",
    url: "https://arcteryx.com.au/collections/outlet",
    websiteUrl: "https://arcteryx.com.au/",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: ["https://arcteryx.com.au/collections/outlet"],
    description: "Arc'teryx Australia outlet for technical outdoor apparel and gear markdowns.",
  },
  {
    name: "Under Armour Outlet Australia",
    url: "https://www.underarmour.com.au/en-au/c/outlet/",
    websiteUrl: "https://www.underarmour.com.au/",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: ["https://www.underarmour.com.au/en-au/c/outlet/"],
    description: "Under Armour outlet with training gear, shoes and sports apparel discounts.",
  },
  {
    name: "Salomon Outlet Australia",
    url: "https://salomon.com.au/collections/outlet",
    websiteUrl: "https://salomon.com.au/",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: ["https://salomon.com.au/collections/outlet"],
    description: "Salomon Australia outlet for trail running, hiking and outdoor gear markdowns.",
  },
  {
    name: "Oxford Outlet Suits",
    url: "https://www.oxfordshop.com.au/collections/mens-outlet-suits",
    websiteUrl: "https://www.oxfordshop.com.au/",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: ["https://www.oxfordshop.com.au/collections/mens-outlet-suits"],
    description: "Oxford outlet suits and business attire sale collection.",
  },
  {
    name: "Typo Outlet Australia",
    url: "https://typo.com/AU/outlet/",
    websiteUrl: "https://typo.com/AU/",
    suburb: "Melbourne CBD",
    city: "Melbourne",
    state: "VIC",
    address: "Melbourne VIC 3000",
    catalogs: ["https://typo.com/AU/outlet/"],
    description: "Typo Australia outlet for stationery, gifts, tech accessories and clearance offers.",
  },
  {
    name: "Bellroy Outlet",
    url: "https://bellroy.com/products/category/outlet",
    websiteUrl: "https://bellroy.com/",
    suburb: "Melbourne CBD",
    city: "Melbourne",
    state: "VIC",
    address: "Melbourne VIC 3000",
    catalogs: ["https://bellroy.com/products/category/outlet"],
    description: "Bellroy outlet with wallets, bags, pouches and carry accessories markdowns.",
  },
];

seedRegionalStores({
  regionName: "Australia",
  categoryName: "Factory Outlets",
  verifierProfile: "retailShop",
  stores,
  maxPages: 5,
  requestTimeoutMs: 12000,
}).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
