import { RegionalStoreSeed, seedRegionalStores } from "./lib/seed-regional-stores";

const officialUrl = "https://www.drmartens.com.au/";
const saleUrl = "https://www.drmartens.com.au/shop/sale";
const saleCatalogs = [
  saleUrl,
  "https://www.drmartens.com.au/shop/sale/womens",
  "https://www.drmartens.com.au/shop/sale/mens",
];

const stores: RegionalStoreSeed[] = [
  {
    name: "Dr. Martens Westfield Sydney",
    url: `${officialUrl}#westfield-sydney-nsw`,
    websiteUrl: officialUrl,
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Westfield Sydney, 100 Market Street, Sydney NSW 2000",
    catalogs: saleCatalogs,
    description: "Official Dr. Martens Australia store listing for boots, shoes, sandals and accessories.",
  },
  {
    name: "Dr. Martens World Square",
    url: `${officialUrl}#world-square-sydney-nsw`,
    websiteUrl: officialUrl,
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "World Square Shopping Centre, 644 George Street, Sydney NSW 2000",
    catalogs: saleCatalogs,
    description: "Official Dr. Martens Australia store listing for boots, shoes, sandals and accessories.",
  },
  {
    name: "Dr. Martens Charlestown Square",
    url: `${officialUrl}#charlestown-square-nsw`,
    websiteUrl: officialUrl,
    suburb: "Charlestown",
    city: "Newcastle",
    state: "NSW",
    address: "Charlestown Square, 30 Pearson Street, Charlestown NSW 2290",
    catalogs: saleCatalogs,
    description: "Official Dr. Martens Australia store listing for boots, shoes, sandals and accessories.",
  },
  {
    name: "Dr. Martens Erina Fair",
    url: `${officialUrl}#erina-fair-nsw`,
    websiteUrl: officialUrl,
    suburb: "Erina",
    city: "Central Coast",
    state: "NSW",
    address: "Erina Fair, Terrigal Drive, Erina NSW 2250",
    catalogs: saleCatalogs,
    description: "Official Dr. Martens Australia store listing for boots, shoes, sandals and accessories.",
  },
  {
    name: "Dr. Martens Melbourne Central",
    url: `${officialUrl}#melbourne-central-vic`,
    websiteUrl: officialUrl,
    suburb: "Melbourne CBD",
    city: "Melbourne",
    state: "VIC",
    address: "Melbourne Central Shopping Centre, 211 La Trobe Street, Melbourne VIC 3000",
    catalogs: saleCatalogs,
    description: "Official Dr. Martens Australia store listing for boots, shoes, sandals and accessories.",
  },
  {
    name: "Dr. Martens Chadstone",
    url: `${officialUrl}#chadstone-vic`,
    websiteUrl: officialUrl,
    suburb: "Chadstone",
    city: "Melbourne",
    state: "VIC",
    address: "Chadstone The Fashion Capital, 1341 Dandenong Road, Chadstone VIC 3148",
    catalogs: saleCatalogs,
    description: "Official Dr. Martens Australia store listing for boots, shoes, sandals and accessories.",
  },
  {
    name: "Dr. Martens Highpoint",
    url: `${officialUrl}#highpoint-vic`,
    websiteUrl: officialUrl,
    suburb: "Maribyrnong",
    city: "Melbourne",
    state: "VIC",
    address: "Highpoint Shopping Centre, 120-200 Rosamond Road, Maribyrnong VIC 3032",
    catalogs: saleCatalogs,
    description: "Official Dr. Martens Australia store listing for boots, shoes, sandals and accessories.",
  },
  {
    name: "Dr. Martens Fountain Gate",
    url: `${officialUrl}#fountain-gate-vic`,
    websiteUrl: officialUrl,
    suburb: "Narre Warren",
    city: "Melbourne",
    state: "VIC",
    address: "Westfield Fountain Gate, 25-55 Overland Drive, Narre Warren VIC 3805",
    catalogs: saleCatalogs,
    description: "Official Dr. Martens Australia store listing for boots, shoes, sandals and accessories.",
  },
  {
    name: "Dr. Martens DFO South Wharf",
    url: `${officialUrl}#dfo-south-wharf-vic`,
    websiteUrl: officialUrl,
    suburb: "South Wharf",
    city: "Melbourne",
    state: "VIC",
    address: "DFO South Wharf, 20 Convention Centre Place, South Wharf VIC 3006",
    catalogs: saleCatalogs,
    description: "Official Dr. Martens Australia store listing for boots, shoes, sandals and accessories.",
  },
  {
    name: "Dr. Martens Pacific Fair",
    url: `${officialUrl}#pacific-fair-qld`,
    websiteUrl: officialUrl,
    suburb: "Broadbeach",
    city: "Gold Coast",
    state: "QLD",
    address: "Pacific Fair Shopping Centre, Hooker Boulevard, Broadbeach QLD 4218",
    catalogs: saleCatalogs,
    description: "Official Dr. Martens Australia store listing for boots, shoes, sandals and accessories.",
  },
  {
    name: "Dr. Martens Westfield Chermside",
    url: `${officialUrl}#westfield-chermside-qld`,
    websiteUrl: officialUrl,
    suburb: "Chermside",
    city: "Brisbane",
    state: "QLD",
    address: "Westfield Chermside, Gympie Road, Chermside QLD 4032",
    catalogs: saleCatalogs,
    description: "Official Dr. Martens Australia store listing for boots, shoes, sandals and accessories.",
  },
  {
    name: "Dr. Martens Westfield Carousel",
    url: `${officialUrl}#westfield-carousel-wa`,
    websiteUrl: officialUrl,
    suburb: "Cannington",
    city: "Perth",
    state: "WA",
    address: "Westfield Carousel, 1382 Albany Highway, Cannington WA 6107",
    catalogs: saleCatalogs,
    description: "Official Dr. Martens Australia store listing for boots, shoes, sandals and accessories.",
  },
];

seedRegionalStores({
  regionName: "Australia",
  categoryName: "Clothing & Fashions",
  verifierProfile: "retailShop",
  stores,
  maxPages: 8,
  requestTimeoutMs: 15000,
  concurrency: 3,
}).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
