import { DiningBeverageVenue, seedDiningBeverageRegion } from "./lib/seed-dining-beverages-region";

const venues: DiningBeverageVenue[] = [
  {
    name: "Fico Hobart",
    url: "https://ficofico.net/",
    suburb: "Hobart",
    city: "Hobart",
    state: "TAS",
    address: "151 Macquarie Street, Hobart TAS 7000",
    catalogs: ["https://ficofico.net/"],
    description: "Hobart fine dining restaurant serving seasonal dinner menus and Tasmanian produce.",
  },
  {
    name: "Aloft Hobart",
    url: "https://aloftrestaurant.com/",
    suburb: "Hobart",
    city: "Hobart",
    state: "TAS",
    address: "Brooke Street Pier, Hobart TAS 7000",
    catalogs: ["https://aloftrestaurant.com/"],
    description: "Waterfront Hobart restaurant serving dinner, drinks and elevated Tasmanian dining.",
  },
  {
    name: "The Glass House Hobart",
    url: "https://www.theglass.house/",
    suburb: "Hobart",
    city: "Hobart",
    state: "TAS",
    address: "Brooke Street Pier, Hobart TAS 7000",
    catalogs: ["https://www.theglass.house/"],
    description: "Hobart waterfront bar and dining room serving cocktails, lunch, dinner and harbour views.",
  },
  {
    name: "Landscape Restaurant Hobart",
    url: "https://www.landscaperestaurant.com.au/",
    suburb: "Hobart",
    city: "Hobart",
    state: "TAS",
    address: "23 Hunter Street, Hobart TAS 7000",
    catalogs: ["https://www.landscaperestaurant.com.au/"],
    description: "Hobart fine dining grill restaurant serving dinner, wine and Tasmanian produce.",
  },
  {
    name: "Hobart Brewing Co",
    url: "https://www.hobartbrewingco.com.au/",
    suburb: "Hobart",
    city: "Hobart",
    state: "TAS",
    address: "16 Evans Street, Hobart TAS 7000",
    catalogs: ["https://www.hobartbrewingco.com.au/", "https://www.hobartbrewingco.com.au/events"],
    description: "Hobart brewery, bar and live-event venue serving beer, food trucks and entertainment.",
  },
  {
    name: "Cascade Brewery Bar Hobart",
    url: "https://cascadebrewerybar.com.au/",
    suburb: "South Hobart",
    city: "Hobart",
    state: "TAS",
    address: "140 Cascade Road, South Hobart TAS 7004",
    catalogs: ["https://cascadebrewerybar.com.au/", "https://cascadebrewerybar.com.au/whats-on/"],
    description: "Historic Hobart brewery bar and restaurant serving lunch, drinks, tours and events.",
  },
  {
    name: "Institut Polaire Hobart",
    url: "https://institutpolaire.com.au/",
    suburb: "Hobart",
    city: "Hobart",
    state: "TAS",
    address: "1/7 Murray Street, Hobart TAS 7000",
    catalogs: ["https://institutpolaire.com.au/"],
    description: "Hobart wine bar and kitchen serving dinner, drinks and Tasmanian produce.",
  },
  {
    name: "Stillwater Launceston",
    url: "https://stillwater.com.au/",
    suburb: "Launceston",
    city: "Launceston",
    state: "TAS",
    address: "2 Bridge Road, Launceston TAS 7250",
    catalogs: ["https://stillwater.com.au/"],
    description: "Launceston restaurant and wine venue serving lunch, dinner and fine Tasmanian dining.",
  },
  {
    name: "Grain of the Silos Launceston",
    url: "https://www.grainofthesilos.com.au/",
    suburb: "Invermay",
    city: "Launceston",
    state: "TAS",
    address: "89-91 Lindsay Street, Invermay TAS 7248",
    catalogs: ["https://www.grainofthesilos.com.au/"],
    description: "Launceston restaurant and bar serving lunch, dinner and regional Tasmanian ingredients.",
  },
  {
    name: "The Den Salamanca",
    url: "https://theden.com.au/",
    suburb: "Battery Point",
    city: "Hobart",
    state: "TAS",
    address: "63 Salamanca Place, Battery Point TAS 7004",
    catalogs: ["https://theden.com.au/"],
    description: "Salamanca cocktail bar and lounge serving drinks, shared plates and late-night Hobart hospitality.",
  },
];

seedDiningBeverageRegion("Tasmania", venues).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
