import { RegionalStoreSeed, seedRegionalStores } from "./lib/seed-regional-stores";

const stores: RegionalStoreSeed[] = [
  {
    name: "Coles Australia",
    url: "https://www.coles.com.au",
    websiteUrl: "https://www.coles.com.au",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: ["https://www.coles.com.au/specials", "https://www.coles.com.au/catalogues"],
    description: "Australian supermarket with weekly grocery specials, catalogue offers and household essentials.",
  },
  {
    name: "Woolworths Australia",
    url: "https://www.woolworths.com.au",
    websiteUrl: "https://www.woolworths.com.au",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: ["https://www.woolworths.com.au/shop/browse/specials", "https://www.woolworths.com.au/shop/catalogue"],
    description: "Australian supermarket with grocery specials, catalogue offers, household staples and fresh food deals.",
  },
  {
    name: "Harris Farm Markets",
    url: "https://www.harrisfarm.com.au",
    websiteUrl: "https://www.harrisfarm.com.au",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: ["https://www.harrisfarm.com.au/collections/specials"],
    description: "Fresh food grocer with fruit, vegetables, pantry goods and weekly specials across NSW.",
  },
  {
    name: "Thai Kee IGA Haymarket",
    url: "https://www.thaikee.com.au/",
    suburb: "Haymarket",
    city: "Sydney",
    state: "NSW",
    address: "Market City, 9-13 Hay Street, Haymarket NSW 2000",
    catalogs: ["https://www.thaikee.com.au/"],
    description: "Asian supermarket in Haymarket offering groceries, fresh food, pantry staples and store promotions.",
  },
  {
    name: "Tong Li Supermarket",
    url: "https://www.tongli.com.au/",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: ["https://www.tongli.com.au/"],
    description: "Asian grocery supermarket group with pantry staples, fresh food and store promotions.",
  },
  {
    name: "Fruitologist Rozelle",
    url: "https://fruitologist.com.au/",
    suburb: "Rozelle",
    city: "Sydney",
    state: "NSW",
    address: "Rozelle NSW 2039",
    catalogs: ["https://fruitologist.com.au/"],
    description: "Sydney greengrocer and providore selling premium fruit, vegetables, pantry items and grocery specials.",
  },
  {
    name: "BWS Australia",
    url: "https://bws.com.au/",
    websiteUrl: "https://bws.com.au/",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: ["https://bws.com.au/specials"],
    description: "Australian beverage retailer with beer, wine, spirits and weekly liquor specials.",
  },
  {
    name: "Dan Murphy's Australia",
    url: "https://www.danmurphys.com.au/",
    websiteUrl: "https://www.danmurphys.com.au/",
    suburb: "Sydney CBD",
    city: "Sydney",
    state: "NSW",
    address: "Sydney NSW 2000",
    catalogs: ["https://www.danmurphys.com.au/offers"],
    description: "Australian beverage retailer with wine, beer, spirits, member offers and catalogue specials.",
  },
];

seedRegionalStores({
  regionName: "NSW",
  categoryName: "Food & Groceries",
  verifierProfile: "retailShop",
  stores,
  maxPages: 5,
  requestTimeoutMs: 12000,
}).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
