import { PrismaClient } from "@prisma/client";
import { getLiveVerifiedOfferEndDate } from "../src/lib/offer-lifecycle";
import { RegionalStoreSeed, seedRegionalStores } from "./lib/seed-regional-stores";

const prisma = new PrismaClient();

const officialUrl = "https://www.harveynorman.com.au/";
const saleCatalogs = [
  "https://www.harveynorman.com.au/clearance/",
  "https://www.harveynorman.com.au/clearance?p=1",
  "https://www.harveynorman.com.au/clearance?p=2",
  "https://www.harveynorman.com.au/sale",
  "https://www.harveynorman.com.au/hot-deals?intcmp=HNAU-7225",
];

const description =
  "Harvey Norman Australia branch for electronics, computers, appliances, furniture and home technology deals.";

const stores: RegionalStoreSeed[] = [
  {
    name: "Harvey Norman Auburn",
    url: `${officialUrl}#auburn-nsw`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Auburn",
    city: "Sydney",
    state: "NSW",
    address: "Harvey Norman Auburn, Auburn NSW 2144",
    latitude: -33.8496,
    longitude: 151.0331,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Broadway",
    url: `${officialUrl}#broadway-nsw`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Broadway",
    city: "Sydney",
    state: "NSW",
    address: "Harvey Norman Broadway, Broadway NSW 2007",
    latitude: -33.8833,
    longitude: 151.1937,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Moore Park",
    url: `${officialUrl}#moore-park-nsw`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Moore Park",
    city: "Sydney",
    state: "NSW",
    address: "Harvey Norman Moore Park, Moore Park NSW 2021",
    latitude: -33.8951,
    longitude: 151.2137,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Balgowlah",
    url: `${officialUrl}#balgowlah-nsw`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Balgowlah",
    city: "Sydney",
    state: "NSW",
    address: "Harvey Norman Balgowlah, Balgowlah NSW 2093",
    latitude: -33.7948,
    longitude: 151.2634,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Blacktown",
    url: `${officialUrl}#blacktown-nsw`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Blacktown",
    city: "Sydney",
    state: "NSW",
    address: "Harvey Norman Blacktown, Blacktown NSW 2148",
    latitude: -33.771,
    longitude: 150.9063,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Campbelltown",
    url: `${officialUrl}#campbelltown-nsw`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Campbelltown",
    city: "Sydney",
    state: "NSW",
    address: "Harvey Norman Campbelltown, Campbelltown NSW 2560",
    latitude: -34.0667,
    longitude: 150.8142,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Liverpool",
    url: `${officialUrl}#liverpool-nsw`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Liverpool",
    city: "Sydney",
    state: "NSW",
    address: "Harvey Norman Liverpool, Liverpool NSW 2170",
    latitude: -33.9209,
    longitude: 150.9236,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Penrith",
    url: `${officialUrl}#penrith-nsw`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Penrith",
    city: "Sydney",
    state: "NSW",
    address: "Harvey Norman Penrith, Penrith NSW 2750",
    latitude: -33.7512,
    longitude: 150.6942,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Caringbah",
    url: `${officialUrl}#caringbah-nsw`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Caringbah",
    city: "Sydney",
    state: "NSW",
    address: "Harvey Norman Caringbah, Caringbah NSW 2229",
    latitude: -34.041,
    longitude: 151.124,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Kotara",
    url: `${officialUrl}#kotara-nsw`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Kotara",
    city: "Newcastle",
    state: "NSW",
    address: "Harvey Norman Kotara, Kotara NSW 2289",
    latitude: -32.941,
    longitude: 151.711,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Warrawong",
    url: `${officialUrl}#warrawong-nsw`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Warrawong",
    city: "Wollongong",
    state: "NSW",
    address: "Harvey Norman Warrawong, Warrawong NSW 2502",
    latitude: -34.485,
    longitude: 150.889,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Fyshwick",
    url: `${officialUrl}#fyshwick-act`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Fyshwick",
    city: "Canberra",
    state: "ACT",
    address: "Harvey Norman Fyshwick, Fyshwick ACT 2609",
    latitude: -35.3307,
    longitude: 149.1697,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Chadstone",
    url: `${officialUrl}#chadstone-vic`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Chadstone",
    city: "Melbourne",
    state: "VIC",
    address: "Harvey Norman Chadstone, Chadstone VIC 3148",
    latitude: -37.8878,
    longitude: 145.0823,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Maribyrnong",
    url: `${officialUrl}#maribyrnong-vic`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Maribyrnong",
    city: "Melbourne",
    state: "VIC",
    address: "Harvey Norman Maribyrnong, Maribyrnong VIC 3032",
    latitude: -37.7727,
    longitude: 144.8841,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Moorabbin",
    url: `${officialUrl}#moorabbin-vic`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Moorabbin",
    city: "Melbourne",
    state: "VIC",
    address: "Harvey Norman Moorabbin, Moorabbin VIC 3189",
    latitude: -37.9402,
    longitude: 145.057,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Preston",
    url: `${officialUrl}#preston-vic`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Preston",
    city: "Melbourne",
    state: "VIC",
    address: "Harvey Norman Preston, Preston VIC 3072",
    latitude: -37.7388,
    longitude: 145.0015,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Nunawading",
    url: `${officialUrl}#nunawading-vic`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Nunawading",
    city: "Melbourne",
    state: "VIC",
    address: "Harvey Norman Nunawading, Nunawading VIC 3131",
    latitude: -37.8207,
    longitude: 145.1764,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Geelong",
    url: `${officialUrl}#geelong-vic`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Geelong",
    city: "Geelong",
    state: "VIC",
    address: "Harvey Norman Geelong, Geelong VIC 3220",
    latitude: -38.1499,
    longitude: 144.3617,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Bundall",
    url: `${officialUrl}#bundall-qld`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Bundall",
    city: "Gold Coast",
    state: "QLD",
    address: "Harvey Norman Bundall, Bundall QLD 4217",
    latitude: -28.011,
    longitude: 153.413,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Fortitude Valley",
    url: `${officialUrl}#fortitude-valley-qld`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Fortitude Valley",
    city: "Brisbane",
    state: "QLD",
    address: "Harvey Norman Fortitude Valley, Fortitude Valley QLD 4006",
    latitude: -27.455,
    longitude: 153.035,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Carindale",
    url: `${officialUrl}#carindale-qld`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Carindale",
    city: "Brisbane",
    state: "QLD",
    address: "Harvey Norman Carindale, Carindale QLD 4152",
    latitude: -27.506,
    longitude: 153.101,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Aspley",
    url: `${officialUrl}#aspley-qld`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Aspley",
    city: "Brisbane",
    state: "QLD",
    address: "Harvey Norman Aspley, Aspley QLD 4034",
    latitude: -27.366,
    longitude: 153.016,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Toowoomba",
    url: `${officialUrl}#toowoomba-qld`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Toowoomba",
    city: "Toowoomba",
    state: "QLD",
    address: "Harvey Norman Toowoomba, Toowoomba QLD 4350",
    latitude: -27.5598,
    longitude: 151.9507,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Cairns",
    url: `${officialUrl}#cairns-qld`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Cairns",
    city: "Cairns",
    state: "QLD",
    address: "Harvey Norman Cairns, Cairns QLD 4870",
    latitude: -16.9186,
    longitude: 145.7781,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Townsville",
    url: `${officialUrl}#townsville-qld`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Townsville",
    city: "Townsville",
    state: "QLD",
    address: "Harvey Norman Townsville, Townsville QLD 4810",
    latitude: -19.2589,
    longitude: 146.8169,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Adelaide",
    url: `${officialUrl}#adelaide-sa`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Adelaide",
    city: "Adelaide",
    state: "SA",
    address: "Harvey Norman Adelaide, Adelaide SA 5000",
    latitude: -34.9285,
    longitude: 138.6007,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Marion",
    url: `${officialUrl}#marion-sa`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Marion",
    city: "Adelaide",
    state: "SA",
    address: "Harvey Norman Marion, Marion SA 5043",
    latitude: -35.016,
    longitude: 138.554,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Gepps Cross",
    url: `${officialUrl}#gepps-cross-sa`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Gepps Cross",
    city: "Adelaide",
    state: "SA",
    address: "Harvey Norman Gepps Cross, Gepps Cross SA 5094",
    latitude: -34.842,
    longitude: 138.6,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Cannington",
    url: `${officialUrl}#cannington-wa`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Cannington",
    city: "Perth",
    state: "WA",
    address: "Harvey Norman Cannington, Cannington WA 6107",
    latitude: -32.016,
    longitude: 115.937,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Osborne Park",
    url: `${officialUrl}#osborne-park-wa`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Osborne Park",
    city: "Perth",
    state: "WA",
    address: "Harvey Norman Osborne Park, Osborne Park WA 6017",
    latitude: -31.91,
    longitude: 115.817,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Joondalup",
    url: `${officialUrl}#joondalup-wa`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Joondalup",
    city: "Perth",
    state: "WA",
    address: "Harvey Norman Joondalup, Joondalup WA 6027",
    latitude: -31.744,
    longitude: 115.766,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Midland",
    url: `${officialUrl}#midland-wa`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Midland",
    city: "Perth",
    state: "WA",
    address: "Harvey Norman Midland, Midland WA 6056",
    latitude: -31.889,
    longitude: 116.008,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Hobart",
    url: `${officialUrl}#hobart-tas`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Hobart",
    city: "Hobart",
    state: "TAS",
    address: "Harvey Norman Hobart, Hobart TAS 7000",
    latitude: -42.8821,
    longitude: 147.3272,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Launceston",
    url: `${officialUrl}#launceston-tas`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Launceston",
    city: "Launceston",
    state: "TAS",
    address: "Harvey Norman Launceston, Launceston TAS 7250",
    latitude: -41.4332,
    longitude: 147.1441,
    catalogs: saleCatalogs,
    description,
  },
  {
    name: "Harvey Norman Darwin",
    url: `${officialUrl}#darwin-nt`,
    websiteUrl: officialUrl,
    verificationUrl: "https://www.harveynorman.com.au/clearance/",
    suburb: "Darwin",
    city: "Darwin",
    state: "NT",
    address: "Harvey Norman Darwin, Darwin NT 0800",
    latitude: -12.4634,
    longitude: 130.8456,
    catalogs: saleCatalogs,
    description,
  },
];

async function copyParentOfferToBranches() {
  const now = new Date();
  const category = await prisma.category.findUnique({ where: { name: "Electronic & Gadgets" } });
  if (!category) {
    return;
  }

  const parent = await prisma.store.findFirst({
    where: {
      categoryId: category.id,
      name: "Harvey Norman",
      locationSource: { not: "suburb" },
    },
    include: {
      discounts: {
        where: {
          endDate: {
            gte: now,
          },
        },
      },
    },
  });
  const branches = await prisma.store.findMany({
    where: {
      categoryId: category.id,
      name: { startsWith: "Harvey Norman " },
      locationSource: "suburb",
    },
  });
  const parentOffer = parent?.discounts.find((discount) => discount.title === "Happening Now...") || parent?.discounts[0];
  const offer = parentOffer
    ? {
        title: "Happening Now...",
        description: parentOffer.description || "Harvey Norman sale, clearance or hot-deal wording found. Check the store website for live availability.",
        startDate: parentOffer.startDate,
        endDate: parentOffer.endDate,
        eCatalog: parentOffer.eCatalog.length > 0 ? parentOffer.eCatalog : saleCatalogs,
        coupon: parentOffer.coupon,
      }
    : {
        title: "Happening Now...",
        description: "Harvey Norman sale, clearance and hot-deal pages are available. Check the store website for live availability.",
        startDate: now,
        endDate: getLiveVerifiedOfferEndDate(now, "retailShop"),
        eCatalog: saleCatalogs,
        coupon: undefined,
      };

  for (const branch of branches) {
    await prisma.discount.upsert({
      where: {
        storeId_title: {
          storeId: branch.id,
          title: offer.title,
        },
      },
      update: {
        description: offer.description,
        startDate: offer.startDate,
        endDate: offer.endDate,
        eCatalog: offer.eCatalog,
        coupon: offer.coupon,
        updatedAt: new Date(),
      },
      create: {
        storeId: branch.id,
        ...offer,
      },
    });
  }

  console.log(`Copied Harvey Norman offer to ${branches.length} branch stores.`);
}

seedRegionalStores({
  regionName: "Australia-wide",
  categoryName: "Electronic & Gadgets",
  verifierProfile: "retailShop",
  stores,
  verify: false,
}).then(copyParentOfferToBranches)
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
