import { DiningBeverageVenue, seedDiningBeverageRegion } from "./lib/seed-dining-beverages-region";

const venues: DiningBeverageVenue[] = [
  {
    name: "Attica Ripponlea",
    url: "https://www.attica.com.au/",
    suburb: "Ripponlea",
    city: "Melbourne",
    state: "VIC",
    address: "74 Glen Eira Road, Ripponlea VIC 3185",
    catalogs: ["https://www.attica.com.au/"],
    description: "Internationally recognised Melbourne fine dining restaurant serving degustation dinner experiences.",
  },
  {
    name: "Vue de Monde Melbourne",
    url: "https://vuedemonde.com.au/",
    suburb: "Melbourne",
    city: "Melbourne",
    state: "VIC",
    address: "Rialto Towers, 525 Collins Street, Melbourne VIC 3000",
    catalogs: ["https://vuedemonde.com.au/"],
    description: "Melbourne fine dining restaurant serving elevated lunch, dinner and skyline dining.",
  },
  {
    name: "Gimlet Melbourne",
    url: "https://gimlet.melbourne/",
    suburb: "Melbourne",
    city: "Melbourne",
    state: "VIC",
    address: "33 Russell Street, Melbourne VIC 3000",
    catalogs: ["https://gimlet.melbourne/"],
    description: "CBD dining room and cocktail bar serving lunch, dinner and late-night drinks.",
  },
  {
    name: "Reine and La Rue Melbourne",
    url: "https://reineandlarue.melbourne/",
    suburb: "Melbourne",
    city: "Melbourne",
    state: "VIC",
    address: "380 Collins Street, Melbourne VIC 3000",
    catalogs: ["https://reineandlarue.melbourne/"],
    description: "Melbourne restaurant and bar serving French-inspired lunch, dinner and cocktail service.",
  },
  {
    name: "Society Melbourne",
    url: "https://societyrestaurant.com/",
    suburb: "Melbourne",
    city: "Melbourne",
    state: "VIC",
    address: "80 Collins Street, Melbourne VIC 3000",
    catalogs: ["https://societyrestaurant.com/"],
    description: "High-end Melbourne restaurant, lounge and bar serving fine dining, lunch, dinner and cocktails.",
  },
  {
    name: "Eau De Vie Melbourne",
    url: "https://eaudevie.com.au/melbourne/",
    websiteUrl: "https://eaudevie.com.au/",
    suburb: "Melbourne",
    city: "Melbourne",
    state: "VIC",
    address: "1 Malthouse Lane, Melbourne VIC 3000",
    catalogs: ["https://eaudevie.com.au/melbourne/"],
    description: "Melbourne cocktail bar and supper-club style venue serving refined drinks and small plates.",
  },
  {
    name: "Cherry Bar Melbourne",
    url: "https://www.cherrybar.com.au/",
    suburb: "Melbourne",
    city: "Melbourne",
    state: "VIC",
    address: "68 Little Collins Street, Melbourne VIC 3000",
    catalogs: ["https://www.cherrybar.com.au/"],
    description: "Melbourne rock bar and live music venue serving drinks, late nights and entertainment.",
  },
  {
    name: "Hotel Esplanade St Kilda",
    url: "https://hotelesplanade.com.au/",
    suburb: "St Kilda",
    city: "Melbourne",
    state: "VIC",
    address: "11 The Esplanade, St Kilda VIC 3182",
    catalogs: ["https://hotelesplanade.com.au/", "https://hotelesplanade.com.au/whats-on/"],
    description: "Iconic St Kilda pub, restaurant, bar and live music venue serving lunch, dinner and events.",
  },
  {
    name: "Lucien St Kilda",
    url: "https://www.lucienbar.au/",
    suburb: "St Kilda",
    city: "Melbourne",
    state: "VIC",
    address: "St Kilda VIC 3182",
    catalogs: ["https://www.lucienbar.au/"],
    description: "French restaurant and cocktail bar in St Kilda with live piano and dinner service.",
  },
  {
    name: "Little Lygon Bar Carlton",
    url: "https://littlelygonbar.com.au/",
    suburb: "Carlton",
    city: "Melbourne",
    state: "VIC",
    address: "Lygon Street, Carlton VIC 3053",
    catalogs: ["https://littlelygonbar.com.au/"],
    description: "Carlton bar and dining venue with live music, drinks and evening hospitality.",
  },
];

seedDiningBeverageRegion("Victoria", venues).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
