import { DiningBeverageVenue, seedDiningBeverageRegion } from "./lib/seed-dining-beverages-region";

const venues: DiningBeverageVenue[] = [
  {
    name: "Wildflower Perth",
    url: "https://wildflowerperth.com.au/",
    suburb: "Perth",
    city: "Perth",
    state: "WA",
    address: "COMO The Treasury, 1 Cathedral Avenue, Perth WA 6000",
    catalogs: ["https://wildflowerperth.com.au/"],
    description: "Perth fine dining restaurant serving lunch, dinner and Western Australian produce-led menus.",
  },
  {
    name: "Long Chim Perth",
    url: "https://www.longchimperth.com/",
    suburb: "Perth",
    city: "Perth",
    state: "WA",
    address: "Basement, State Buildings, Saint Georges Terrace, Perth WA 6000",
    catalogs: ["https://www.longchimperth.com/"],
    description: "Perth Thai restaurant and bar serving lunch, dinner and lively dining in the State Buildings.",
  },
  {
    name: "Balthazar Perth",
    url: "https://balthazar.com.au/",
    suburb: "Perth",
    city: "Perth",
    state: "WA",
    address: "6 The Esplanade, Perth WA 6000",
    catalogs: ["https://balthazar.com.au/"],
    description: "Perth restaurant and wine bar serving lunch, dinner and refined CBD dining.",
  },
  {
    name: "Mechanics Institute Bar Perth",
    url: "https://www.mechanicsinstitutebar.com.au/",
    suburb: "Northbridge",
    city: "Perth",
    state: "WA",
    address: "222 William Street, Northbridge WA 6003",
    catalogs: ["https://www.mechanicsinstitutebar.com.au/"],
    description: "Northbridge rooftop cocktail bar serving drinks, bar snacks and late-night Perth hospitality.",
  },
  {
    name: "The Rechabite Northbridge",
    url: "https://therechabite.com.au/",
    suburb: "Northbridge",
    city: "Perth",
    state: "WA",
    address: "224 William Street, Northbridge WA 6003",
    catalogs: ["https://therechabite.com.au/", "https://therechabite.com.au/whats-on/"],
    description: "Northbridge live performance venue, bar and dining destination with rooftop and event programming.",
  },
  {
    name: "Shadow Wine Bar Northbridge",
    url: "https://shadowwinebar.com.au/",
    suburb: "Northbridge",
    city: "Perth",
    state: "WA",
    address: "214 William Street, Northbridge WA 6003",
    catalogs: ["https://shadowwinebar.com.au/"],
    description: "Northbridge wine bar and restaurant serving dinner, drinks and late-night dining.",
  },
  {
    name: "Miki's Open Kitchen Margaret River",
    url: "https://www.mikisopenkitchen.com.au/",
    suburb: "Margaret River",
    city: "Margaret River",
    state: "WA",
    address: "131 Bussell Highway, Margaret River WA 6285",
    catalogs: ["https://www.mikisopenkitchen.com.au/"],
    description: "Margaret River Japanese fine dining venue serving omakase-style dinner experiences.",
  },
  {
    name: "Leeuwin Estate Restaurant Margaret River",
    url: "https://leeuwinestate.com.au/",
    suburb: "Witchcliffe",
    city: "Margaret River",
    state: "WA",
    address: "Stevens Road, Witchcliffe WA 6286",
    catalogs: ["https://leeuwinestate.com.au/", "https://leeuwinestate.com.au/restaurant/"],
    description: "Margaret River winery restaurant serving lunch, wine experiences and estate dining.",
  },
  {
    name: "Yarri Restaurant Dunsborough",
    url: "https://yarri.com.au/",
    suburb: "Dunsborough",
    city: "Busselton",
    state: "WA",
    address: "16 Cyrillean Way, Dunsborough WA 6281",
    catalogs: ["https://yarri.com.au/"],
    description: "Dunsborough restaurant and bar serving dinner, drinks and Margaret River region produce.",
  },
  {
    name: "Morries Margaret River",
    url: "https://morries.com.au/",
    suburb: "Margaret River",
    city: "Margaret River",
    state: "WA",
    address: "149 Bussell Highway, Margaret River WA 6285",
    catalogs: ["https://morries.com.au/"],
    description: "Margaret River bar and restaurant serving dinner, cocktails, tapas and live hospitality.",
  },
];

seedDiningBeverageRegion("Western Australia", venues).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
