import { DiningBeverageVenue, seedDiningBeverageRegion } from "./lib/seed-dining-beverages-region";

const venues: DiningBeverageVenue[] = [
  {
    name: "Boom Boom Room Brisbane",
    url: "https://www.theboomboomroom.com.au/",
    suburb: "Brisbane City",
    city: "Brisbane",
    state: "QLD",
    address: "49 Elizabeth Street, Brisbane City QLD 4000",
    catalogs: ["https://www.theboomboomroom.com.au/"],
    description: "Brisbane supper club with modern Asian dining, late-night cocktails and live entertainment.",
  },
  {
    name: "Agnes Restaurant Brisbane",
    url: "https://agnesrestaurant.com.au/",
    suburb: "Fortitude Valley",
    city: "Brisbane",
    state: "QLD",
    address: "22 Agnes Street, Fortitude Valley QLD 4006",
    catalogs: ["https://agnesrestaurant.com.au/"],
    description: "Brisbane wood-fired restaurant and bar serving lunch, dinner and elevated dining.",
  },
  {
    name: "Honto Fortitude Valley",
    url: "https://honto.com.au/",
    suburb: "Fortitude Valley",
    city: "Brisbane",
    state: "QLD",
    address: "Alden Street, Fortitude Valley QLD 4006",
    catalogs: ["https://honto.com.au/"],
    description: "Japanese-inspired Fortitude Valley restaurant and bar serving dinner and cocktails.",
  },
  {
    name: "Blackbird Bar and Grill Brisbane",
    url: "https://blackbirdbrisbane.com.au/",
    suburb: "Brisbane City",
    city: "Brisbane",
    state: "QLD",
    address: "Riverside Centre, 123 Eagle Street, Brisbane City QLD 4000",
    catalogs: ["https://blackbirdbrisbane.com.au/", "https://blackbirdbrisbane.com.au/whats-on/"],
    description: "Brisbane riverfront steakhouse, restaurant and bar serving lunch, dinner, cocktails and events.",
  },
  {
    name: "Savile Row Brisbane",
    url: "https://www.savilerowbrisbane.com.au/",
    suburb: "Fortitude Valley",
    city: "Brisbane",
    state: "QLD",
    address: "667 Ann Street, Fortitude Valley QLD 4006",
    catalogs: ["https://www.savilerowbrisbane.com.au/"],
    description: "Hidden Fortitude Valley cocktail bar serving late-night drinks and curated bar experiences.",
  },
  {
    name: "Rick Shores Burleigh Heads",
    url: "https://rickshores.com.au/",
    suburb: "Burleigh Heads",
    city: "Gold Coast",
    state: "QLD",
    address: "43 Goodwin Terrace, Burleigh Heads QLD 4220",
    catalogs: ["https://rickshores.com.au/"],
    description: "Beachfront Gold Coast restaurant serving lunch, dinner, cocktails and coastal dining.",
  },
  {
    name: "Etsu Izakaya Mermaid Beach",
    url: "https://etsu.com.au/",
    suburb: "Mermaid Beach",
    city: "Gold Coast",
    state: "QLD",
    address: "2440 Gold Coast Highway, Mermaid Beach QLD 4218",
    catalogs: ["https://etsu.com.au/"],
    description: "Gold Coast Japanese izakaya and bar serving dinner, sake and late-night dining.",
  },
  {
    name: "The North Room Mermaid Beach",
    url: "https://thenorthroom.com.au/",
    suburb: "Mermaid Beach",
    city: "Gold Coast",
    state: "QLD",
    address: "2527 Gold Coast Highway, Mermaid Beach QLD 4218",
    catalogs: ["https://thenorthroom.com.au/"],
    description: "Intimate Gold Coast restaurant serving refined dinner, drinks and contemporary coastal dining.",
  },
  {
    name: "Nu Nu Palm Cove",
    url: "https://www.nunu.com.au/",
    suburb: "Palm Cove",
    city: "Cairns",
    state: "QLD",
    address: "123 Williams Esplanade, Palm Cove QLD 4879",
    catalogs: ["https://www.nunu.com.au/"],
    description: "Palm Cove beachfront restaurant serving lunch, dinner and tropical North Queensland dining.",
  },
  {
    name: "Hemingway's Brewery Cairns Wharf",
    url: "https://hemingwaysbrewery.com/",
    suburb: "Cairns City",
    city: "Cairns",
    state: "QLD",
    address: "4 Wharf Street, Cairns City QLD 4870",
    catalogs: ["https://hemingwaysbrewery.com/"],
    description: "Cairns waterfront brewery, restaurant and bar serving lunch, dinner, drinks and events.",
  },
];

seedDiningBeverageRegion("Queensland", venues).catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
